apiVersion: v1
data:
  api-config.yaml: ZGF0YWJhc2U6CiAgICBob3N0OiBteXNxbAogICAgdXNlcm5hbWU6IHRhc2thcHBfdXNlcgogICAgcGFzc3dvcmQ6IDJIY1ZDX2EyeFFGb29EdmIKICAgIGRibmFtZTogdGFza2FwcAogICAgbWF4SWRsZUNvbm5zOiA1CiAgICBtYXhPcGVuQ29ubnM6IDEwCiAgICBjb25uTWF4TGlmZXRpbWU6IDFoMG0wcwo=
kind: Secret
metadata:
  creationTimestamp: null
  name: api-config
